// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.11.4
// source: models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GyroRaw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *GyroRaw) Reset() {
	*x = GyroRaw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GyroRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GyroRaw) ProtoMessage() {}

func (x *GyroRaw) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GyroRaw.ProtoReflect.Descriptor instead.
func (*GyroRaw) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *GyroRaw) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GyroRaw) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GyroRaw) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type AccRaw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *AccRaw) Reset() {
	*x = AccRaw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccRaw) ProtoMessage() {}

func (x *AccRaw) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccRaw.ProtoReflect.Descriptor instead.
func (*AccRaw) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *AccRaw) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AccRaw) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AccRaw) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Angles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Angles) Reset() {
	*x = Angles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Angles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Angles) ProtoMessage() {}

func (x *Angles) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Angles.ProtoReflect.Descriptor instead.
func (*Angles) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{2}
}

func (x *Angles) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Angles) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SensorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GyroRaw *GyroRaw `protobuf:"bytes,1,opt,name=gyroRaw,proto3" json:"gyroRaw,omitempty"`
	AccRaw  *AccRaw  `protobuf:"bytes,2,opt,name=accRaw,proto3" json:"accRaw,omitempty"`
	Angles  *Angles  `protobuf:"bytes,3,opt,name=angles,proto3" json:"angles,omitempty"`
	Esc     float32  `protobuf:"fixed32,4,opt,name=esc,proto3" json:"esc,omitempty"`
}

func (x *SensorEvent) Reset() {
	*x = SensorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEvent) ProtoMessage() {}

func (x *SensorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEvent.ProtoReflect.Descriptor instead.
func (*SensorEvent) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{3}
}

func (x *SensorEvent) GetGyroRaw() *GyroRaw {
	if x != nil {
		return x.GyroRaw
	}
	return nil
}

func (x *SensorEvent) GetAccRaw() *AccRaw {
	if x != nil {
		return x.AccRaw
	}
	return nil
}

func (x *SensorEvent) GetAngles() *Angles {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *SensorEvent) GetEsc() float32 {
	if x != nil {
		return x.Esc
	}
	return 0
}

var File_models_models_proto protoreflect.FileDescriptor

var file_models_models_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x07, 0x47, 0x79, 0x72, 0x6f, 0x52, 0x61, 0x77,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x32, 0x0a, 0x06, 0x41, 0x63,
	0x63, 0x52, 0x61, 0x77, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x24,
	0x0a, 0x06, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x67, 0x79, 0x72, 0x6f, 0x52, 0x61, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x47, 0x79, 0x72, 0x6f, 0x52, 0x61, 0x77, 0x52,
	0x07, 0x67, 0x79, 0x72, 0x6f, 0x52, 0x61, 0x77, 0x12, 0x1f, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x52,
	0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41, 0x63, 0x63, 0x52, 0x61,
	0x77, 0x52, 0x06, 0x61, 0x63, 0x63, 0x52, 0x61, 0x77, 0x12, 0x1f, 0x0a, 0x06, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41, 0x6e, 0x67, 0x6c,
	0x65, 0x73, 0x52, 0x06, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x73,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x73, 0x63, 0x42, 0x09, 0x5a, 0x07,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_models_proto_rawDescOnce sync.Once
	file_models_models_proto_rawDescData = file_models_models_proto_rawDesc
)

func file_models_models_proto_rawDescGZIP() []byte {
	file_models_models_proto_rawDescOnce.Do(func() {
		file_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_models_proto_rawDescData)
	})
	return file_models_models_proto_rawDescData
}

var file_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_models_proto_goTypes = []interface{}{
	(*GyroRaw)(nil),     // 0: GyroRaw
	(*AccRaw)(nil),      // 1: AccRaw
	(*Angles)(nil),      // 2: Angles
	(*SensorEvent)(nil), // 3: SensorEvent
}
var file_models_models_proto_depIdxs = []int32{
	0, // 0: SensorEvent.gyroRaw:type_name -> GyroRaw
	1, // 1: SensorEvent.accRaw:type_name -> AccRaw
	2, // 2: SensorEvent.angles:type_name -> Angles
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_models_proto_init() }
func file_models_models_proto_init() {
	if File_models_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GyroRaw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccRaw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Angles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_models_proto_goTypes,
		DependencyIndexes: file_models_models_proto_depIdxs,
		MessageInfos:      file_models_models_proto_msgTypes,
	}.Build()
	File_models_models_proto = out.File
	file_models_models_proto_rawDesc = nil
	file_models_models_proto_goTypes = nil
	file_models_models_proto_depIdxs = nil
}
