/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "models.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GyroRaw, GyroRaw, AUTO)


PB_BIND(AccRaw, AccRaw, AUTO)


PB_BIND(Angles, Angles, AUTO)


PB_BIND(SensorEvent, SensorEvent, AUTO)



