/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_MODELS_MODELS_PB_H_INCLUDED
#define PB_MODELS_MODELS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AccRaw { 
    float x;
    float y;
    float z;
} AccRaw;

typedef struct _Angles { 
    float x;
    float y;
} Angles;

typedef struct _GyroRaw { 
    float x;
    float y;
    float z;
} GyroRaw;

typedef struct _SensorEvent { 
    bool has_gyroRaw;
    GyroRaw gyroRaw;
    bool has_accRaw;
    AccRaw accRaw;
    bool has_angles;
    Angles angles;
    float esc;
} SensorEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define GyroRaw_init_default                     {0, 0, 0}
#define AccRaw_init_default                      {0, 0, 0}
#define Angles_init_default                      {0, 0}
#define SensorEvent_init_default                 {false, GyroRaw_init_default, false, AccRaw_init_default, false, Angles_init_default, 0}
#define GyroRaw_init_zero                        {0, 0, 0}
#define AccRaw_init_zero                         {0, 0, 0}
#define Angles_init_zero                         {0, 0}
#define SensorEvent_init_zero                    {false, GyroRaw_init_zero, false, AccRaw_init_zero, false, Angles_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AccRaw_x_tag                             1
#define AccRaw_y_tag                             2
#define AccRaw_z_tag                             3
#define Angles_x_tag                             1
#define Angles_y_tag                             2
#define GyroRaw_x_tag                            1
#define GyroRaw_y_tag                            2
#define GyroRaw_z_tag                            3
#define SensorEvent_gyroRaw_tag                  1
#define SensorEvent_accRaw_tag                   2
#define SensorEvent_angles_tag                   3
#define SensorEvent_esc_tag                      4

/* Struct field encoding specification for nanopb */
#define GyroRaw_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define GyroRaw_CALLBACK NULL
#define GyroRaw_DEFAULT NULL

#define AccRaw_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define AccRaw_CALLBACK NULL
#define AccRaw_DEFAULT NULL

#define Angles_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2)
#define Angles_CALLBACK NULL
#define Angles_DEFAULT NULL

#define SensorEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gyroRaw,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accRaw,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  angles,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    esc,               4)
#define SensorEvent_CALLBACK NULL
#define SensorEvent_DEFAULT NULL
#define SensorEvent_gyroRaw_MSGTYPE GyroRaw
#define SensorEvent_accRaw_MSGTYPE AccRaw
#define SensorEvent_angles_MSGTYPE Angles

extern const pb_msgdesc_t GyroRaw_msg;
extern const pb_msgdesc_t AccRaw_msg;
extern const pb_msgdesc_t Angles_msg;
extern const pb_msgdesc_t SensorEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GyroRaw_fields &GyroRaw_msg
#define AccRaw_fields &AccRaw_msg
#define Angles_fields &Angles_msg
#define SensorEvent_fields &SensorEvent_msg

/* Maximum encoded size of messages (where known) */
#define AccRaw_size                              15
#define Angles_size                              10
#define GyroRaw_size                             15
#define SensorEvent_size                         51

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
